[package]
name = "mock-ref-exchange"
version = "1.8.0"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
uint = { version = "0.9.5", default-features = false }
near-sdk = "4.1.1"
near-contract-standards = "4.1.1"
once_cell = "1.18.0"
near-sys = "=0.2"
